#!/usr/bin/env python3
"""
OpenClaw Task Chain Handler
監聽任務完成事件，自動產生後續任務
"""

import json
import os
import subprocess
from datetime import datetime
from pathlib import Path

WORKSPACE = Path.home() / ".openclaw" / "workspace"
TASK_FILE = WORKSPACE / "memory" / "task-board.json"
CHAIN_RULES_FILE = WORKSPACE / "task-chain-rules.json"

# 任務鏈規則定義
DEFAULT_CHAIN_RULES = {
    "rules": [
        {
            "name": "早晨檢查鏈",
            "trigger": "早晨檢查",
            "next_tasks": [
                {
                    "name": "整理早晨檢查結果",
                    "description": "將早晨檢查的郵件、日曆、天氣資訊整理成報告",
                    "delay_minutes": 0
                }
            ]
        },
        {
            "name": "郵件處理鏈",
            "trigger": "檢查郵件",
            "next_tasks": [
                {
                    "name": "分類重要郵件",
                    "description": "將郵件分為緊急、重要、普通三類",
                    "delay_minutes": 5
                },
                {
                    "name": "產生回覆草稿",
                    "description": "為重要郵件產生回覆草稿",
                    "delay_minutes": 15
                }
            ]
        },
        {
            "name": "Git 監控鏈",
            "trigger": "監控專案 git 狀態",
            "next_tasks": [
                {
                    "name": "提交變更報告",
                    "description": "如有未提交變更，產生提交報告",
                    "delay_minutes": 0,
                    "condition": "has_changes"
                }
            ]
        },
        {
            "name": "晚間總結鏈",
            "trigger": "晚間總結",
            "next_tasks": [
                {
                    "name": "建立明日待辦",
                    "description": "根據今日總結建立明日待辦清單",
                    "delay_minutes": 0
                }
            ]
        }
    ]
}

def load_rules():
    """載入任務鏈規則"""
    if not CHAIN_RULES_FILE.exists():
        with open(CHAIN_RULES_FILE, 'w') as f:
            json.dump(DEFAULT_CHAIN_RULES, f, indent=2, ensure_ascii=False)
        return DEFAULT_CHAIN_RULES
    
    with open(CHAIN_RULES_FILE) as f:
        return json.load(f)

def load_tasks():
    """載入任務列表"""
    if not TASK_FILE.exists():
        return {"tasks": [], "stats": {}}
    
    with open(TASK_FILE) as f:
        return json.load(f)

def save_tasks(data):
    """儲存任務列表"""
    with open(TASK_FILE, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def create_task(name, description, agent="main", status="pending"):
    """建立新任務"""
    data = load_tasks()
    
    new_task = {
        "id": f"task-{datetime.now().timestamp()}-{os.urandom(4).hex()}",
        "name": name,
        "description": description,
        "agent": agent,
        "status": status,
        "createdAt": datetime.now().isoformat(),
        "updatedAt": datetime.now().isoformat(),
        "autoGenerated": True,
        "parentTask": None  # 可在未來擴充
    }
    
    data['tasks'].append(new_task)
    data['stats']['totalCreated'] = data['stats'].get('totalCreated', 0) + 1
    
    save_tasks(data)
    print(f"✅ 自動建立任務：{name}")
    return new_task

def check_completed_tasks():
    """檢查已完成的任務，觸發任務鏈"""
    data = load_tasks()
    rules = load_rules()
    
    completed_tasks = [t for t in data['tasks'] 
                       if t['status'] == 'completed' 
                       and not t.get('chainProcessed', False)]
    
    for task in completed_tasks:
        # 查找匹配的規則
        for rule in rules['rules']:
            if rule['trigger'] in task['name'] or task['name'] in rule['trigger']:
                print(f"🔗 觸發任務鏈：{rule['name']} (由 {task['name']})")
                
                # 建立後續任務
                for next_task in rule['next_tasks']:
                    # 檢查條件（如果有）
                    if 'condition' in next_task:
                        if not check_condition(next_task['condition'], task):
                            continue
                    
                    create_task(
                        name=next_task['name'],
                        description=next_task['description'],
                        agent=task.get('agent', 'main')
                    )
                
                # 標記為已處理
                task['chainProcessed'] = True
                task['chainProcessedAt'] = datetime.now().isoformat()
                break
    
    save_tasks(data)

def check_condition(condition, task):
    """檢查條件是否滿足"""
    if condition == "has_changes":
        # 檢查 git 是否有變更
        try:
            result = subprocess.run(
                ['git', 'status', '--porcelain'],
                cwd=WORKSPACE,
                capture_output=True,
                text=True
            )
            return bool(result.stdout.strip())
        except:
            return False
    return True

def log_activity(message):
    """記錄活動日誌"""
    log_file = WORKSPACE / "memory" / "task-chain.log"
    timestamp = datetime.now().isoformat()
    with open(log_file, 'a') as f:
        f.write(f"[{timestamp}] {message}\n")

def main():
    """主程式"""
    print("🦞 OpenClaw Task Chain Handler")
    print("監聽任務完成事件...")
    print()
    
    # 立即檢查一次
    check_completed_tasks()
    
    # 之後每 30 秒檢查一次
    import time
    while True:
        time.sleep(30)
        check_completed_tasks()

if __name__ == "__main__":
    main()
